import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { headers } from 'next/headers'
import { type ReactNode } from 'react'
import { cookieToInitialState } from 'wagmi'

import { getConfig } from '../lib/wagmi'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Wagmi',
  description: 'Generated by create-wagmi',
}

// ✅ Convert RootLayout to an async function
export default async function RootLayout({ children }: { children: ReactNode }) {
  // ✅ Await headers() before accessing cookies
  const cookieHeader = (await headers()).get('cookie')
  const initialState = cookieToInitialState(getConfig(), cookieHeader)

  return (
    <html lang="en">
      <head>
        {/* Add metadata dynamically if needed */}
      </head>
      <body className={inter.className}>
        <Providers initialState={initialState}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
